spring.application.name=drm
spring.profiles.include=db
rsa.public.key.path=./public.pem
rsa.private.key.path=./private.pem
temp.file.save.path=./tempFiles/
temp.file.crypt.path=./cryptFile/
drm.header.signature=wan_DRM@1013
logging.level.root=debug
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=35MB
server.forward-headers-strategy=framework
password.iteration=10000
app.init.admin=false
app.init.guest=false
app.init.pem=false
default.admin.account=admin
default.guest.account=guest
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html