spring.application.name=drm
spring.profiles.include=db
rsa.public.key.path=${PUBLIC_KEY_PATH:./public.pem}
rsa.private.key.path=${PRIVATE_KEY_PATH:./private.pem}
temp.file.save.path=${TEMP_FILE_PATH:./tempFiles/}
temp.file.crypt.path=${CRYPTO_FILE_PATH:./cryptFile/}
drm.header.signature=${DRM_SIGN:wan_DRM@1013}
logging.level.root=debug
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=35MB
server.forward-headers-strategy=framework
password.iteration=10000
app.init.admin=${INIT_ADMIN_ACCOUNT:false}
app.init.pem=${INIT_PEM:false}
default.admin.account=admin
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html